#!/usr/bin/env python3
"""
Generate seed positions for the general/multi-piece solver (-DPIECE_GENERAL),
for ANY combination of White pieces -- one script, not one per material
combination. Black stays a lone king, matching the engine's current scope.

WHY THIS IS A DIFFERENT KIND OF SCRIPT THAN generate_list_kqvk_ordering.py /
generate_list_krvk_ordering.py, NOT JUST A GENERALIZED VERSION OF THEM:

Those scripts exist because the single-attacker engine's --full-dag only
follows TIED-OPTIMAL moves outward from each seed, not every legal move --
so it needs many seeds, spread across the whole DTZ range, to get good
coverage of the state space, and Syzygy DTZ ordering lets nearby positions
reuse already-solved neighbors as a cache.

The general/multi-piece engine's RetrogradeClassifier works completely
differently: discovery follows EVERY legal move for BOTH sides from each
seed. That means a single seed already reaches the ENTIRE connected
component of same-material positions (confirmed directly and repeatedly:
every KQvK regression position produced the identical 372,064-node
discovered graph, regardless of which specific position it started from).
So you do NOT need an exhaustive, Syzygy-ranked enumeration here -- you need
a small number of valid starting positions chosen carefully enough to
guarantee full reachability, which is a much easier problem.

THE ONE REAL SUBTLETY: pawns only move forward. A seed with a pawn already
on, say, rank 6 can only discover positions with that pawn on rank 6 or
higher -- it can never discover earlier ranks, because forward-only
discovery can't run time backward. So any material including a pawn MUST be
seeded with the pawn on its starting rank (rank 2 for White), which lets
forward-only exploration naturally reach every later rank up through
promotion. This script enforces that automatically.

Multiple seeds (spread across different board regions) are generated by
default purely as a safety margin against the possibility of more than one
disconnected component for unusual material -- extra seeds only add
coverage, never subtract it, since the classifier's discovery function
already deduplicates instantly on any already-known position.

Usage:
    python3 generate_general_seed_positions.py --white Q --out kqvk_seeds.txt
    python3 generate_general_seed_positions.py --white B,P --out kbpvk_seeds.txt
    python3 generate_general_seed_positions.py --white B,N --out kbnvk_seeds.txt --num-seeds 12
"""

import argparse
import itertools


PIECE_LETTERS = {'Q', 'R', 'B', 'N', 'P'}


class Position:
    def __init__(self, file, rank):
        self.file = file
        self.rank = rank

    def __eq__(self, other):
        return self.file == other.file and self.rank == other.rank

    def __hash__(self):
        return hash((self.file, self.rank))

    def distance_to(self, other):
        return max(abs(self.file - other.file), abs(self.rank - other.rank))

    def to_str(self):
        return chr(ord('a') + self.file) + str(self.rank + 1)


def parse_white_pieces(spec):
    """'B,P' -> ['B', 'P']. Validates against the letters the C++ engine's
    parser (PieceKind, kind_from_letter equivalents) actually recognizes."""
    letters = [s.strip().upper() for s in spec.split(',') if s.strip()]
    if not letters:
        raise ValueError("--white must name at least one piece")
    for l in letters:
        if l not in PIECE_LETTERS:
            if len(l) > 1 and all(c in PIECE_LETTERS for c in l):
                # Almost certainly meant comma-separated pieces but typed
                # them run together (e.g. 'BN' or 'bn' instead of 'B,N') --
                # a real, easy mistake to make, and the old plain "not a
                # valid letter" error gave no hint toward the actual fix.
                suggestion = ",".join(l)
                raise ValueError(f"'{l}' is not a valid single piece letter -- did you mean "
                                  f"comma-separated, like --white {suggestion} ?")
            raise ValueError(f"Unrecognized piece letter '{l}' -- must be one of {sorted(PIECE_LETTERS)}")
    return letters


def _slides_clear(from_pos, to_pos, occupied):
    """True if the straight-line (rank, file, or diagonal) path between two
    squares has no occupied square strictly between them. Assumes the two
    squares are already known to be aligned (same rank/file/diagonal)."""
    df = to_pos.file - from_pos.file
    dr = to_pos.rank - from_pos.rank
    step_f = (df > 0) - (df < 0)
    step_r = (dr > 0) - (dr < 0)
    f, r = from_pos.file + step_f, from_pos.rank + step_r
    while (f, r) != (to_pos.file, to_pos.rank):
        if (f, r) in occupied:
            return False
        f += step_f
        r += step_r
    return True


def _attacks(letter, from_pos, target, occupied):
    """Does a White piece of this kind, sitting at from_pos, attack target,
    given the full set of occupied squares (for blocking sliders)? Pawn
    direction is hardcoded White-forward, matching the fact that every seed
    this generator produces has White pieces only doing the attacking here."""
    df = target.file - from_pos.file
    dr = target.rank - from_pos.rank
    if df == 0 and dr == 0:
        return False
    upper = letter.upper()
    if upper == 'K':
        return max(abs(df), abs(dr)) == 1
    if upper == 'N':
        return (abs(df), abs(dr)) in ((1, 2), (2, 1))
    if upper == 'P':
        return dr == 1 and abs(df) == 1
    if upper == 'B':
        return abs(df) == abs(dr) and _slides_clear(from_pos, target, occupied)
    if upper == 'R':
        return (df == 0 or dr == 0) and _slides_clear(from_pos, target, occupied)
    if upper == 'Q':
        return ((abs(df) == abs(dr) or df == 0 or dr == 0)
                and _slides_clear(from_pos, target, occupied))
    return False


def is_legal_placement(squares, white_letters=None):
    """Mirrors the C++ engine's is_legal_state: every piece on a distinct
    square, and the two kings not adjacent. squares is a dict of
    role -> Position, where role is 'WK', 'BK', or a piece index.

    Also rejects any placement leaving Black's king already attacked by a
    White piece -- every seed this generator produces is White-to-move by
    construction, and "White to move, Black already in check" is not a
    reachable chess position: it would mean Black's own last move left its
    king in check, which is illegal. Confirmed as a REAL, not theoretical,
    gap: checked directly against every exhaustive KBNvK seed and found
    583 of 3612 (16.14%) violated exactly this, all flagged by python-chess
    as STATUS_OPPOSITE_CHECK when cross-checked independently. This only
    taints the seed row itself, never anything discovered from it --
    generate_legal_moves in the engine checks "does this move leave the
    CURRENT mover in check" fresh at every position, with no dependency on
    how that position was reached, so every child is independently correct
    regardless of whether its ancestor seed was a reachable position."""
    positions = list(squares.values())
    if len(set((p.file, p.rank) for p in positions)) != len(positions):
        return False
    if squares['WK'].distance_to(squares['BK']) < 2:
        return False

    if white_letters is not None:
        occupied = {(p.file, p.rank) for p in positions}
        white_pieces = [('K', squares['WK'])]
        for i, letter in enumerate(white_letters):
            key = f'W{i}'
            if key in squares:
                white_pieces.append((letter, squares[key]))
        for letter, pos in white_pieces:
            if _attacks(letter, pos, squares['BK'], occupied):
                return False

    return True


def square_color(pos):
    """DARK if (file+rank) is even (a1 = file 0, rank 0 = DARK, matching
    real chess), LIGHT if odd. A bishop's square color is conserved by
    every legal bishop move -- diagonal steps change file and rank by the
    same amount, so file+rank always changes by an even number. This means
    a light-squared-bishop position and a dark-squared-bishop position are
    NEVER reachable from one another: the full landscape for any material
    including a bishop is (at least) two structurally disconnected
    components, one per bishop color, not one connected whole."""
    return 'dark' if (pos.file + pos.rank) % 2 == 0 else 'light'


def all_squares_list():
    return [Position(f, r) for r in range(8) for f in range(8)]


def enumerate_fully_exhaustive(white_letters, bishop_color=None):
    """Yields (white_letters, squares_dict, turn) for EVERY legal position
    of this material -- true combinatorial enumeration over every piece's
    square, not just king pairs with one fixed placement rule for
    everything else. This is what "exhaustive" needs to mean to match a
    real, Syzygy-style completeness guarantee: nothing is skipped because
    of how some OTHER piece happens to be placed for a given king pair.

    Supports 0, 1, or 2 non-king White pieces (the engine's current
    scope). Yields both White-to-move and Black-to-move positions --
    White-to-move seeds are filtered to exclude Black already being in
    check (illegal/unreachable, per is_legal_placement's own docstring);
    Black-to-move seeds need no such filter in this scope, since Black
    has no piece capable of attacking White's king (a bare king only
    attacks adjacent squares, already excluded by the king-distance
    check)."""
    ALL = all_squares_list()

    for wk in ALL:
        wk_key = (wk.file, wk.rank)
        for bk in ALL:
            if bk == wk or wk.distance_to(bk) < 2:
                continue
            bk_key = (bk.file, bk.rank)
            base_used = {wk_key, bk_key}

            def candidates_for(letter, used):
                if letter == 'P':
                    return [p for p in ALL if p.rank == 1 and (p.file, p.rank) not in used]
                if letter == 'B' and bishop_color is not None:
                    return [p for p in ALL if square_color(p) == bishop_color and (p.file, p.rank) not in used]
                return [p for p in ALL if (p.file, p.rank) not in used]

            if len(white_letters) == 0:
                combos = [()]
            elif len(white_letters) == 1:
                combos = [(p,) for p in candidates_for(white_letters[0], base_used)]
            elif len(white_letters) == 2:
                combos = []
                for p0 in candidates_for(white_letters[0], base_used):
                    used1 = base_used | {(p0.file, p0.rank)}
                    for p1 in candidates_for(white_letters[1], used1):
                        combos.append((p0, p1))
            else:
                raise ValueError("only 0, 1, or 2 non-king White pieces are supported by this engine")

            for combo in combos:
                squares = {'WK': wk, 'BK': bk}
                for i, p in enumerate(combo):
                    squares[f'W{i}'] = p

                occupied = base_used | {(p.file, p.rank) for p in combo}
                white_pieces = [('K', wk)] + list(zip(white_letters, combo))

                # White-to-move: Black must not already be in check.
                if not any(_attacks(letter, pos, bk, occupied) for letter, pos in white_pieces):
                    yield (white_letters, dict(squares), 'W')

                # Black-to-move: nothing to check in this scope (see docstring).
                yield (white_letters, dict(squares), 'B')



def build_seed(white_letters, anchor, force_bishop_color=None):
    """Constructs one valid seed position anchored near a given corner/region
    of the board, so successive seeds are genuinely spread out rather than
    clustered -- see the module docstring for why this is only a defensive
    margin, not something correctness depends on.

    force_bishop_color ('light', 'dark', or None): if set and 'B' is among
    white_letters, the bishop is placed ONLY on a square of that color --
    see square_color's docstring for why this matters. Used to generate
    seeds for exactly one bishop-color component at a time, so each half
    can be discovered and classified separately (roughly halving peak
    memory for any material with exactly one bishop) instead of needing
    both colors' full reachable graphs in memory simultaneously."""
    af, ar = anchor
    all_squares = [Position(f, r) for r in range(8) for f in range(8)]
    pool = sorted(all_squares, key=lambda p: (abs(p.file - af) + abs(p.rank - ar), p.file, p.rank))

    squares = {}
    used = set()

    def take_next(predicate=lambda p: True):
        for p in pool:
            if (p.file, p.rank) in used:
                continue
            if not predicate(p):
                continue
            used.add((p.file, p.rank))
            return p
        raise RuntimeError("ran out of candidate squares -- should not happen on an 8x8 board")

    squares['WK'] = take_next()
    squares['BK'] = take_next(lambda p: p.distance_to(squares['WK']) >= 2)

    def not_attacking_bk(letter):
        return lambda p: not _attacks(letter, p, squares['BK'], used)

    for i, letter in enumerate(white_letters):
        if letter == 'P':
            candidates = sorted((Position(f, 1) for f in range(8)), key=lambda p: abs(p.file - af))
            placed = False
            for cand in candidates:
                if (cand.file, cand.rank) not in used and not _attacks('P', cand, squares['BK'], used):
                    used.add((cand.file, cand.rank))
                    squares[f'W{i}'] = cand
                    placed = True
                    break
            if not placed:
                raise RuntimeError("could not place pawn on rank 2 without checking Black's king -- board too crowded")
        elif letter == 'B' and force_bishop_color is not None:
            squares[f'W{i}'] = take_next(lambda p: square_color(p) == force_bishop_color and not_attacking_bk(letter)(p))
        else:
            squares[f'W{i}'] = take_next(not_attacking_bk(letter))

    if not is_legal_placement(squares, white_letters):
        raise RuntimeError("generated placement failed its own legality check -- this is a bug")

    return white_letters, squares


def format_seed(white_letters, squares, turn='W'):
    tokens = [f"K:{squares['WK'].to_str()}"]
    for i, letter in enumerate(white_letters):
        tokens.append(f"{letter}:{squares[f'W{i}'].to_str()}")
    tokens.append(f"k:{squares['BK'].to_str()}")
    if turn == 'B':
        tokens.append("turn:B")
    return ",".join(tokens)


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument('--white', required=True,
                     help="Comma-separated White piece letters, e.g. 'Q' or 'B,P' or 'B,N'")
    ap.add_argument('--out', required=True, help="Output positions file")
    ap.add_argument('--num-seeds', type=int, default=8,
                     help="How many diverse seed positions to generate (default 8; more costs nothing "
                          "at discovery time, since already-known positions are skipped instantly)")
    ap.add_argument('--bishop-color', choices=['light', 'dark'], default=None,
                     help="Constrain the bishop to only light- or dark-squared placements -- "
                          "generates seeds for exactly one of the two structurally disconnected "
                          "halves of the landscape (a bishop's square color never changes under "
                          "any legal move). Use this to discover/classify each half separately, "
                          "roughly halving peak memory for material with one bishop.")
    args = ap.parse_args()

    white_letters = parse_white_pieces(args.white)
    has_pawn = 'P' in white_letters
    if has_pawn and white_letters.count('P') > 1:
        raise SystemExit("ERROR: this script and the current engine scope support at most one pawn")
    has_bishop = 'B' in white_letters

    if args.bishop_color and not has_bishop:
        raise SystemExit("ERROR: --bishop-color only makes sense when --white includes 'B'")

    print(f"White pieces: {white_letters}" + (" (pawn -> all seeds forced to rank 2)" if has_pawn else ""))
    if has_bishop:
        if args.bishop_color:
            print(f"  Bishop constrained to {args.bishop_color}-squared placements only -- "
                  f"see module docstring: a bishop's square color never changes under any "
                  f"legal move, so this generates seeds for exactly ONE of the two "
                  f"structurally disconnected halves of the full landscape.")
        else:
            print("  NOTE: material includes a bishop, whose square color is conserved for the "
                  "whole game -- the full landscape is two disconnected halves (light-squared "
                  "and dark-squared bishop), not one. This run's seeds are NOT explicitly "
                  "balanced between them; use --bishop-color light / --bishop-color dark to "
                  "generate each half separately and deliberately (recommended for memory-"
                  "constrained machines), or verify after the fact that your seed set actually "
                  "included both colors before trusting a combined run as complete.")

    # Genuinely spread anchor points -- corners, edge midpoints, center --
    # rather than a linear rotation that ends up clustering everything in
    # the same few files. Cycles through this list if more seeds are asked
    # for than there are distinct anchors.
    anchors = [(0, 0), (7, 7), (0, 7), (7, 0), (3, 3), (4, 4), (0, 3), (7, 4),
               (3, 0), (4, 7), (0, 4), (7, 3)]
    seeds = []
    for i in range(args.num_seeds):
        anchor = anchors[i % len(anchors)]
        try:
            seeds.append(build_seed(white_letters, anchor, force_bishop_color=args.bishop_color))
        except RuntimeError as e:
            print(f"  (skipped one candidate seed: {e})")

    if not seeds:
        raise SystemExit("ERROR: failed to generate any valid seed -- try a different --num-seeds")

    with open(args.out, 'w') as f:
        f.write("# seed positions for general_solver --full-dag\n")
        for letters, squares in seeds:
            f.write(format_seed(letters, squares) + "\n")

    print(f"\nWrote {len(seeds)} seed positions to {args.out}")
    print("Preview:")
    for letters, squares in seeds[:5]:
        print(f"  {format_seed(letters, squares)}")
    if len(seeds) > 5:
        print(f"  ... and {len(seeds) - 5} more")

    print("\nReachability note: run general_solver on this file and check the reported")
    print("'Discovery: N positions' count. If you're unsure whether one connected")
    print("component was enough, generate a second file with a different --num-seeds")
    print("and confirm the discovered node count matches -- identical counts are strong")
    print("evidence the whole reachable graph was found either way.")


if __name__ == "__main__":
    main()
