#!/usr/bin/env python3
"""
Generate seed positions for the general/multi-piece solver (-DPIECE_GENERAL),
for ANY combination of White pieces -- one script, not one per material
combination. Black stays a lone king, matching the engine's current scope.

WHY THIS IS A DIFFERENT KIND OF SCRIPT THAN generate_list_kqvk_ordering.py /
generate_list_krvk_ordering.py, NOT JUST A GENERALIZED VERSION OF THEM:

Those scripts exist because the single-attacker engine's --full-dag only
follows TIED-OPTIMAL moves outward from each seed, not every legal move --
so it needs many seeds, spread across the whole DTZ range, to get good
coverage of the state space, and Syzygy DTZ ordering lets nearby positions
reuse already-solved neighbors as a cache.

The general/multi-piece engine's RetrogradeClassifier works completely
differently: discovery follows EVERY legal move for BOTH sides from each
seed. That means a single seed already reaches the ENTIRE connected
component of same-material positions (confirmed directly and repeatedly:
every KQvK regression position produced the identical 372,064-node
discovered graph, regardless of which specific position it started from).
So you do NOT need an exhaustive, Syzygy-ranked enumeration here -- you need
a small number of valid starting positions chosen carefully enough to
guarantee full reachability, which is a much easier problem.

THE ONE REAL SUBTLETY: pawns only move forward. A seed with a pawn already
on, say, rank 6 can only discover positions with that pawn on rank 6 or
higher -- it can never discover earlier ranks, because forward-only
discovery can't run time backward. So any material including a pawn MUST be
seeded with the pawn on its starting rank (rank 2 for White), which lets
forward-only exploration naturally reach every later rank up through
promotion. This script enforces that automatically.

Multiple seeds (spread across different board regions) are generated by
default purely as a safety margin against the possibility of more than one
disconnected component for unusual material -- extra seeds only add
coverage, never subtract it, since the classifier's discovery function
already deduplicates instantly on any already-known position.

Usage:
    python3 generate_general_seed_positions.py --white Q --out kqvk_seeds.txt
    python3 generate_general_seed_positions.py --white B,P --out kbpvk_seeds.txt
    python3 generate_general_seed_positions.py --white B,N --out kbnvk_seeds.txt --num-seeds 12
"""

import argparse
import itertools


PIECE_LETTERS = {'Q', 'R', 'B', 'N', 'P'}


class Position:
    def __init__(self, file, rank):
        self.file = file
        self.rank = rank

    def __eq__(self, other):
        return self.file == other.file and self.rank == other.rank

    def __hash__(self):
        return hash((self.file, self.rank))

    def distance_to(self, other):
        return max(abs(self.file - other.file), abs(self.rank - other.rank))

    def to_str(self):
        return chr(ord('a') + self.file) + str(self.rank + 1)


def parse_white_pieces(spec):
    """'B,P' -> ['B', 'P']. Validates against the letters the C++ engine's
    parser (PieceKind, kind_from_letter equivalents) actually recognizes."""
    letters = [s.strip().upper() for s in spec.split(',') if s.strip()]
    if not letters:
        raise ValueError("--white must name at least one piece")
    for l in letters:
        if l not in PIECE_LETTERS:
            raise ValueError(f"Unrecognized piece letter '{l}' -- must be one of {sorted(PIECE_LETTERS)}")
    return letters


def is_legal_placement(squares):
    """Mirrors the C++ engine's is_legal_state: every piece on a distinct
    square, and the two kings not adjacent. squares is a dict of
    role -> Position, where role is 'WK', 'BK', or a piece index."""
    positions = list(squares.values())
    if len(set((p.file, p.rank) for p in positions)) != len(positions):
        return False
    if squares['WK'].distance_to(squares['BK']) < 2:
        return False
    return True


def square_color(pos):
    """DARK if (file+rank) is even (a1 = file 0, rank 0 = DARK, matching
    real chess), LIGHT if odd. A bishop's square color is conserved by
    every legal bishop move -- diagonal steps change file and rank by the
    same amount, so file+rank always changes by an even number. This means
    a light-squared-bishop position and a dark-squared-bishop position are
    NEVER reachable from one another: the full landscape for any material
    including a bishop is (at least) two structurally disconnected
    components, one per bishop color, not one connected whole."""
    return 'dark' if (pos.file + pos.rank) % 2 == 0 else 'light'


def build_seed(white_letters, anchor, force_bishop_color=None):
    """Constructs one valid seed position anchored near a given corner/region
    of the board, so successive seeds are genuinely spread out rather than
    clustered -- see the module docstring for why this is only a defensive
    margin, not something correctness depends on.

    force_bishop_color ('light', 'dark', or None): if set and 'B' is among
    white_letters, the bishop is placed ONLY on a square of that color --
    see square_color's docstring for why this matters. Used to generate
    seeds for exactly one bishop-color component at a time, so each half
    can be discovered and classified separately (roughly halving peak
    memory for any material with exactly one bishop) instead of needing
    both colors' full reachable graphs in memory simultaneously."""
    af, ar = anchor
    all_squares = [Position(f, r) for r in range(8) for f in range(8)]
    pool = sorted(all_squares, key=lambda p: (abs(p.file - af) + abs(p.rank - ar), p.file, p.rank))

    squares = {}
    used = set()

    def take_next(predicate=lambda p: True):
        for p in pool:
            if (p.file, p.rank) in used:
                continue
            if not predicate(p):
                continue
            used.add((p.file, p.rank))
            return p
        raise RuntimeError("ran out of candidate squares -- should not happen on an 8x8 board")

    squares['WK'] = take_next()
    squares['BK'] = take_next(lambda p: p.distance_to(squares['WK']) >= 2)

    for i, letter in enumerate(white_letters):
        if letter == 'P':
            candidates = sorted((Position(f, 1) for f in range(8)), key=lambda p: abs(p.file - af))
            placed = False
            for cand in candidates:
                if (cand.file, cand.rank) not in used:
                    used.add((cand.file, cand.rank))
                    squares[f'W{i}'] = cand
                    placed = True
                    break
            if not placed:
                raise RuntimeError("could not place pawn on rank 2 -- board too crowded")
        elif letter == 'B' and force_bishop_color is not None:
            squares[f'W{i}'] = take_next(lambda p: square_color(p) == force_bishop_color)
        else:
            squares[f'W{i}'] = take_next()

    if not is_legal_placement(squares):
        raise RuntimeError("generated placement failed its own legality check -- this is a bug")

    return white_letters, squares


def format_seed(white_letters, squares):
    tokens = [f"K:{squares['WK'].to_str()}"]
    for i, letter in enumerate(white_letters):
        tokens.append(f"{letter}:{squares[f'W{i}'].to_str()}")
    tokens.append(f"k:{squares['BK'].to_str()}")
    return ",".join(tokens)


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument('--white', required=True,
                     help="Comma-separated White piece letters, e.g. 'Q' or 'B,P' or 'B,N'")
    ap.add_argument('--out', required=True, help="Output positions file")
    ap.add_argument('--num-seeds', type=int, default=8,
                     help="How many diverse seed positions to generate (default 8; more costs nothing "
                          "at discovery time, since already-known positions are skipped instantly)")
    ap.add_argument('--bishop-color', choices=['light', 'dark'], default=None,
                     help="Constrain the bishop to only light- or dark-squared placements -- "
                          "generates seeds for exactly one of the two structurally disconnected "
                          "halves of the landscape (a bishop's square color never changes under "
                          "any legal move). Use this to discover/classify each half separately, "
                          "roughly halving peak memory for material with one bishop.")
    args = ap.parse_args()

    white_letters = parse_white_pieces(args.white)
    has_pawn = 'P' in white_letters
    if has_pawn and white_letters.count('P') > 1:
        raise SystemExit("ERROR: this script and the current engine scope support at most one pawn")
    has_bishop = 'B' in white_letters

    if args.bishop_color and not has_bishop:
        raise SystemExit("ERROR: --bishop-color only makes sense when --white includes 'B'")

    print(f"White pieces: {white_letters}" + (" (pawn -> all seeds forced to rank 2)" if has_pawn else ""))
    if has_bishop:
        if args.bishop_color:
            print(f"  Bishop constrained to {args.bishop_color}-squared placements only -- "
                  f"see module docstring: a bishop's square color never changes under any "
                  f"legal move, so this generates seeds for exactly ONE of the two "
                  f"structurally disconnected halves of the full landscape.")
        else:
            print("  NOTE: material includes a bishop, whose square color is conserved for the "
                  "whole game -- the full landscape is two disconnected halves (light-squared "
                  "and dark-squared bishop), not one. This run's seeds are NOT explicitly "
                  "balanced between them; use --bishop-color light / --bishop-color dark to "
                  "generate each half separately and deliberately (recommended for memory-"
                  "constrained machines), or verify after the fact that your seed set actually "
                  "included both colors before trusting a combined run as complete.")

    # Genuinely spread anchor points -- corners, edge midpoints, center --
    # rather than a linear rotation that ends up clustering everything in
    # the same few files. Cycles through this list if more seeds are asked
    # for than there are distinct anchors.
    anchors = [(0, 0), (7, 7), (0, 7), (7, 0), (3, 3), (4, 4), (0, 3), (7, 4),
               (3, 0), (4, 7), (0, 4), (7, 3)]
    seeds = []
    for i in range(args.num_seeds):
        anchor = anchors[i % len(anchors)]
        try:
            seeds.append(build_seed(white_letters, anchor, force_bishop_color=args.bishop_color))
        except RuntimeError as e:
            print(f"  (skipped one candidate seed: {e})")

    if not seeds:
        raise SystemExit("ERROR: failed to generate any valid seed -- try a different --num-seeds")

    with open(args.out, 'w') as f:
        f.write("# seed positions for general_solver --full-dag\n")
        for letters, squares in seeds:
            f.write(format_seed(letters, squares) + "\n")

    print(f"\nWrote {len(seeds)} seed positions to {args.out}")
    print("Preview:")
    for letters, squares in seeds[:5]:
        print(f"  {format_seed(letters, squares)}")
    if len(seeds) > 5:
        print(f"  ... and {len(seeds) - 5} more")

    print("\nReachability note: run general_solver on this file and check the reported")
    print("'Discovery: N positions' count. If you're unsure whether one connected")
    print("component was enough, generate a second file with a different --num-seeds")
    print("and confirm the discovered node count matches -- identical counts are strong")
    print("evidence the whole reachable graph was found either way.")


if __name__ == "__main__":
    main()
