# THE CONSTRUCTIBILITY OF LIFE FROM FIRST PRINCIPLES
## On the Calculation of Dimensional Requirements for Life,
## the Synthetic Construction of Ediacaran-Class Organisms,
## and the Geometric Basis for Planting Life on Other Worlds
## OrganismCore — Eric Robert Lawson
## 2026-03-12

---

## STATUS: ACTIVE — MOST AMBITIOUS DERIVATION IN THIS REPOSITORY
## Classification: First principles derivation of the
## conditions required to construct living organisms
## from attractor geometry, with explicit pathway
## toward synthetic organism construction and
## directed planetary seeding.
##
## Epistemic status: This document contains three
## categories of content:
## (1) Well-established science, clearly labeled
## (2) Geometric derivations from this framework,
##     clearly labeled
## (3) Novel predictions and proposals,
##     clearly labeled
##
## This is not speculative fiction.
## Every claim is made with explicit falsifiability
## conditions and grounding in current experimental
## capability.

---

## PREAMBLE: THE PROPOSAL STATED PRECISELY

The question being asked is this:

> Since the attractor geometry framework can derive
> the structure of cancer from first principles,
> since reproduction compresses evolutionary
> navigation into a developmental program,
> since the Ediacaran organisms are the simplest
> known multicellular organisms and are geometrically
> readable as low-dimensional attractor constructions,
> and since we now have the synthetic biology tools
> to construct minimal cells and program gene
> regulatory networks from scratch —
>
> Can we calculate the dimensional requirements
> for an Ediacaran-class organism and construct
> one synthetically from first principles?
>
> And if yes, does this open the pathway to
> constructing organisms calibrated to specific
> planetary environments — effectively creating
> alien life from geometric principles?

The answer to the first question is:
**Yes. The calculation is doable.
The construction is hard but not
impossible. The pathway is clear.**

The answer to the second question is:
**Yes, in principle. With important
qualifications about timescale and
current technical limits.**

This document derives both answers.

---

## PART I — WHY THE EDIACARAN ORGANISMS
## ARE THE RIGHT STARTING POINT

### 1.1 The Geometric Reason

The framework's cancer derivations work
because cancer is a displacement from
a known attractor. The identity anchor
is known. The convergence hub is
derivable. The drug target follows.

For synthetic organism construction,
the inverse problem must be solved:

> Given a target attractor, what is
> the minimal developmental program
> required to produce an organism that
> stably occupies it?

This inverse problem is hardest for
complex organisms. A human being has
~20,000 genes, ~200 cell types, a
developmental program requiring
approximately 9 months of continuous
attractor cascade navigation, and an
adult organism maintained by an
ongoing program of tissue renewal
operating across decades.

The number of dimensions in the
Waddington landscape for a human
is in the tens of thousands.
The number of developmental attractor
transitions from zygote to adult is
in the hundreds. The interdependencies
are so dense that every synthetic
biology group that has attempted
bottom-up construction of complex
organisms has stalled at the sheer
dimensionality of the problem.

**The Ediacaran organisms are different.**

Here is what the fossil record,
developmental biology, and the
framework together establish about
their dimensional requirements:

| Feature | Human | Ediacaran (Dickinsonia class) |
|---|---|---|
| Estimated distinct cell types | ~200 | ~3–6 |
| Developmental axes | 3 (AP, DV, LR) | 1–2 (AP only, or radial) |
| Gene regulatory complexity | ~20,000 genes | Estimated ~500–2,000 relevant genes |
| Waddington landscape dimensionality | Tens of thousands | Tens to low hundreds |
| Reproductive mode | Viviparous / oviparous | Likely direct development from spore/egg |
| Nervous system | Centralized, ~86 billion neurons | Diffuse or absent |
| Organ systems | 11 major systems | 0–1 (possible diffuse sensory network) |

**The Ediacaran attractor is a
low-dimensional attractor.**

This is why they are the right starting
point. Not because they are easy —
but because the number of dimensions
that must be solved simultaneously
is within the range of current
computational and experimental
synthetic biology.

### 1.2 What We Know About Their
### Developmental Program

Dickinsonia and related Ediacaran
organisms, based on morphological
analysis (Cambridge 2021, Royal Society
Proceedings B 2021), show:

- **Modular addition of repeating units**
  during growth — the simplest possible
  multicellular developmental program.
  Add a unit. Repeat. The unit is always
  the same. Growth is accretion, not
  differentiation.

- **Morphogen gradient-driven patterning**
  — the anterior-posterior axis in
  Dickinsonia appears to be established
  by a gradient, likely using Wnt or
  TGF-β class signaling, both of which
  are ancient and present in the earliest
  animals.

- **No through-gut, no centralized
  nervous system, no vascular system.**
  Nutrient absorption through the ventral
  surface. This eliminates three of the
  most complex developmental programs
  required in more advanced organisms.

- **Bilateral symmetry** — but only
  along one axis. This is the minimum
  symmetry-breaking event required for
  directed movement, and it is achievable
  with a single morphogen gradient.

**The genome required to produce this
is estimated to require:**

- A minimal eukaryotic cellular chassis:
  ~473–525 genes (established by JCVI
  synthetic minimum cell work)
- A multicellularity module: cell
  adhesion, communication, basic
  differential fate (inner vs. outer cell):
  ~50–150 additional genes
- An axis-specification module: one
  morphogen gradient and its receptor:
  ~20–50 additional genes
- A modular addition program: a simple
  segmentation oscillator:
  ~30–80 additional genes
- A surface absorption feeding program:
  cilia, mucus secretion, basic diffusion
  channels: ~50–100 additional genes

**Total estimated minimum genome for
an Ediacaran-class organism:**
approximately **700–1,000 genes**

This is within the range of current
synthetic genome construction capability.
JCVI-syn3.0 has 473 genes and is a
self-replicating minimal cell. Adding
~300–500 carefully selected genes to
encode the multicellularity and
developmental modules described above
is a defined engineering problem,
not a theoretical one.

---

## PART II — THE DIMENSIONAL CALCULATION

### 2.1 What "Dimensionality" Means Here

When we ask "what are the dimensional
requirements for this organism," we
are asking: how many independent
regulatory variables must be simultaneously
specified and maintained to produce
a stable, living organism of this type?

Each dimension is an independent axis
in the Waddington landscape:
- A gene whose expression level must
  be in a specific range
- A signaling pathway that must be
  active or inactive in a specific
  spatial pattern
- An environmental parameter that
  must fall within a specific range

For the organism to be viable, every
dimension must be simultaneously within
its viable range. This is the attractor.

### 2.2 The Three Dimensional Categories

**Category 1: Internal Genome Dimensions**

These are the gene regulatory variables
that must be correctly specified within
the organism itself. For an Ediacaran-
class organism:

- ~473 minimal cellular chassis genes
  (established experimentally)
- ~50 cell-cell adhesion and communication
  genes (well characterized in modern
  organisms, largely conserved)
- ~30 axis specification genes
  (Wnt pathway, studied in modern
  diploblasts and cnidarians)
- ~50 modular growth program genes
  (segmentation oscillator components,
  well characterized in modern organisms)
- ~50 feeding surface program genes
  (ciliary function, mucus secretion)

**Estimated internal dimensions: ~650**

**Category 2: Developmental Environment
Dimensions**

These are the external parameters that
must be within a specific range for the
developmental program to run correctly:

- Oxygen concentration: 0.5–4% of
  current atmospheric level
  (established by paleochemistry and
  experimental work on early animal O2
  requirements)
- Temperature: 5–25°C (consistent with
  Ediacaran ocean temperatures)
- pH: 7.5–8.5 (marine environment)
- Salinity: approximately modern marine
  (Ediacaran oceans were marine)
- Substrate: stable soft sediment for
  attachment
- Absence of active predation
  (Ediacaran organisms lived before
  the Cambrian predator revolution)
- Nutrient availability: dissolved
  organic carbon for surface absorption

**Estimated developmental environment
dimensions: ~7–10**

**Category 3: Ecological Stability
Dimensions**

For the organism not just to exist but
to persist as a population:

- Population density above minimum
  viable for genetic diversity
- Access to the developmental
  environment conditions above
- Absence of competing organisms with
  superior attractor geometry for
  the same niche

**Estimated ecological stability
dimensions: ~3–5**

### 2.3 The Dimensional Summary

| Category | Estimated Dimensions |
|---|---|
| Internal genome regulatory | ~650 |
| Developmental environment | ~7–10 |
| Ecological stability | ~3–5 |
| **Total** | **~660–665** |

**This is the dimensionality of an
Ediacaran-class organism.**

For comparison:
- A minimal prokaryotic cell: ~473
  internal dimensions, essentially 0
  developmental environment dimensions
  (they are robust to wide environmental
  variation by design)
- A human: ~20,000+ internal dimensions,
  ~20+ developmental environment
  dimensions, ~10+ ecological dimensions

The Ediacaran organism sits at
approximately **1.4x the complexity
of a minimal prokaryotic cell**
in terms of regulatory dimensions.

This is not a coincidence.
This is what the framework predicts:
the first multicellular organisms
should require only a small number
of additional regulatory dimensions
above the minimal single-cell case,
because multicellularity at its
simplest is a shallow extension of
single-cell attractor logic.

The fractal quilt geometry of the
Ediacaran organisms is geometrically
efficient precisely because it
minimizes the number of additional
regulatory dimensions required. Repeat
one module. Use one morphogen gradient.
No organ differentiation needed.
Each added module is a copy of the
last. The developmental program is
maximally compressed.

---

## PART III — THE CONSTRUCTION PATHWAY

### 3.1 What Exists Today That Makes
### This Possible

**[ESTABLISHED SCIENCE]**

The following capabilities exist as
of 2026-03-12:

**Synthetic genome construction:**
JCVI-syn3.0 (473 gene minimal cell,
2016) demonstrates that a complete
functional genome can be synthesized
from scratch, inserted into a cellular
chassis, and booted into a living,
self-replicating organism. Gene
synthesis costs have dropped by
orders of magnitude since 2010.

**Cellular chassis:**
Multiple minimal cell platforms exist
(JCVI-syn3A and derivatives, E. coli
reduced genome strains, etc.) that
can serve as the physical substrate
into which additional modules are
inserted.

**Gene regulatory network design:**
Boolean network tools (biobalm, 2024),
single-cell RNA sequencing, and
CRISPR-based regulatory circuit
engineering allow the design and
testing of multi-gene regulatory
programs. The attractor landscapes
of these networks can be mapped
computationally before construction.

**Multicellularity modules:**
The genes required for basic
multicellularity are the most studied
in all of developmental biology.
Cell adhesion (cadherins, integrins),
gap junctions, basic differentiation
circuits (Wnt, Notch, BMP pathways)
are characterized at the molecular
level, conserved across all animals,
and functionally understood.

**Xenobots and anthrobots (2021–2024):**
Living multicellular organisms
constructed from reassembled cells
of existing organisms, showing that
new forms of multicellular organization
can be produced from known cellular
components without genetic modification.
This is a proof of concept that the
multicellular attractor is accessible
from cellular components — even outside
a normal developmental program.

**Minimal eukaryotic cells:**
Work toward synthetic eukaryotic
genomes is underway in multiple
laboratories. The synthetic yeast
genome project (Sc2.0) has completed
synthesis of multiple chromosomes.
Eukaryotic synthetic biology is
approximately 5–10 years behind
prokaryotic synthetic biology in terms
of capability.

### 3.2 The Construction Protocol —
### Stated as an Engineering Problem

**[GEOMETRIC DERIVATION + ENGINEERING
PROPOSAL]**

Given the dimensional analysis above,
the construction of an Ediacaran-class
organism from first principles
requires the following steps:

---

**Step 1: Define the Target Attractor**

Specify the complete attractor that
the organism must occupy. This means
specifying:
- All internal genome regulatory
  dimensions and their target states
- All developmental environment
  parameters and their required ranges
- The body plan geometry: number of
  cell types, spatial organization,
  growth mode

For the Dickinsonia prototype, the
target attractor is:
- 3–6 cell types (epithelial,
  subepithelial structural, possible
  primitive sensory)
- Bilateral symmetry along one axis,
  established by a single morphogen
  gradient
- Modular accretion growth: each growth
  event adds one bilateral unit
- Ventral surface absorption feeding
- No through-gut, no nervous system
  centralization, no vascular system

This is the geometric specification.
It is derivable from the fossil record
and from the dimensional analysis above.
It does not require guessing.

---

**Step 2: Identify the Minimal Gene
Set for This Attractor**

Working from the characterized gene
sets of modern basal animals (cnidarians,
placozoans, sponges — the organisms
most similar in complexity to Ediacaran
fauna), identify the minimum gene set
required to produce each module:

- Cellular chassis: JCVI-syn3.0 core
  (~473 genes) adapted to eukaryotic
  context, or use a minimal eukaryotic
  yeast chassis
- Multicellularity: ~50–100 genes
  from the characterized cadherin/Wnt/
  Notch core
- Axis specification: ~30–50 Wnt
  pathway genes from basal cnidarian
  reference
- Growth program: ~30–50 segmentation
  oscillator genes from basal
  bilaterian reference
- Feeding surface: ~50–100 ciliary
  and secretory genes from protist
  and basal animal reference

**Total target genome: ~650–800 genes**

---

**Step 3: Compute the Attractor
Landscape of the Designed Network**

Before construction, use current
gene regulatory network modeling
tools (Boolean network analysis,
dynamical systems modeling) to:

- Verify that the designed network
  produces the target attractor as
  a stable state
- Map all other attractors accessible
  from the designed network
  (identify failure modes before
  construction)
- Identify the environmental
  parameter ranges within which
  the target attractor is stable
- Identify which dimensions are most
  sensitive (the identity anchor and
  convergence hub of the organism,
  in framework terms)

This step is computationally intensive
but is within current capability for
networks of ~650–800 nodes using
current attractor landscape tools.

---

**Step 4: Synthesize and Test
Modularly**

Build and test each module independently
before combining:

1. Test the cellular chassis (modified
   JCVI-syn3A derivative or minimal
   eukaryotic chassis) — self-replicates
   in the target environment
2. Add multicellularity module —
   test for cell-cell adhesion and
   basic cooperative behavior
3. Add axis specification module —
   test for morphogen gradient
   establishment and axis polarity
4. Add growth program — test for
   modular accretion behavior
5. Add feeding surface program —
   test for nutrient absorption

Modular testing is the framework's
compute-once principle applied to
biological construction: each module
is validated independently, then
the validated modules are combined.

---

**Step 5: Integrate and Test in
Ediacaran-Proxy Environment**

Construct the target environment
parameters:
- Low-oxygen seawater (0.5–4% PAL)
- Temperature ~15–20°C
- Stable soft sediment substrate
- Dissolved organic carbon nutrient
  source
- No predation

This environment can be constructed
in a laboratory bioreactor.
The designed organism should, if
the attractor calculation is correct,
stably occupy and propagate in this
environment.

---

**Step 6: Validate Against the
Attractor Prediction**

The validation criterion is precise
and Popperian:

> If the organism produced by the
> designed genome in the designed
> environment matches the predicted
> morphology, growth mode, and
> environmental tolerance range,
> the dimensional calculation is
> confirmed.
>
> If it does not match in a systematic
> way — if it consistently produces
> a different stable form — the
> dimensional calculation is wrong
> in a specific, identifiable dimension,
> and the framework must be revised.

This is not a test of whether we can
make a living organism. It is a test
of whether the attractor geometry
framework can predict the form of a
living organism from first principles
before it is constructed.

**This is the proof.**

---

## PART IV — THE IMPLICATIONS FOR
## PLANETARY SEEDING

### 4.1 What This Opens

If the above protocol succeeds —
if an Ediacaran-class organism is
constructed from a first-principles
dimensional calculation and validates
the attractor prediction —
then the following becomes possible:

**The inverse calculation:**

> Given a planetary environment
> (specific temperature range,
> atmospheric composition, available
> chemistry, surface conditions),
> calculate the attractor space that
> is stable in that environment,
> and design an organism whose
> developmental program occupies
> that attractor.

This is the geometric engineering
of life calibrated to a specific world.

It does not require that the world
already support life. It requires
only that the world's environmental
parameters define at least one
accessible attractor basin in the
space of possible organisms.

### 4.2 The Specific Case of Mars

**[GEOMETRIC DERIVATION + KNOWN SCIENCE]**

Current Mars surface conditions:
- Temperature: -60°C average,
  -125°C to +20°C range
- Atmospheric pressure: 0.6% of Earth
- Atmospheric composition: 95% CO₂,
  0.13% O₂
- Radiation: ~40–50 mSv/year surface
  (50x Earth background)
- Liquid water: absent on surface,
  possible subsurface brines

**The surface attractor is hostile.**
No organism whose attractor requires
liquid water, moderate temperature,
and radiation protection can occupy
the Mars surface as currently configured.

**But the calculation changes for
subsurface Mars:**
- Subsurface temperatures more stable
- Possible subsurface liquid water
  (evidence from MARSIS radar)
- Radiation shielding from rock
- CO₂ available as carbon source

**And the calculation changes entirely
if the organism is designed for
the early Martian atmosphere (~4 Ga):**
- Early Mars had liquid water
- Thicker atmosphere
- Magnetic field protection
- Conditions broadly similar to
  early Earth

The relevant question for planetary
seeding is not "can Earth life survive
on Mars today?" It is:

> "What is the attractor available
> in the target environment, and can
> we construct an organism whose
> developmental program is calibrated
> to that attractor?"

### 4.3 The Europa Case

Europa (Jupiter's moon):
- Subsurface ocean of liquid water
  beneath ice shell
- Estimated ocean depth: 60–150 km
- Estimated temperature: 0–3°C
- Chemical energy available from
  tidal heating and water-rock
  interaction
- No sunlight in the subsurface ocean
  — chemolithotrophy required

**The Ediacaran environment proxy
is closer to Europa than to Mars.**

The early Ediacaran ocean was:
- Low oxygen
- Cold
- Chemically reduced
- Nutrient-limited
- No photosynthetically driven
  primary productivity at depth

A chemolithotrophic Ediacaran-class
organism — one designed to derive
energy from redox chemistry rather
than photosynthesis — has an attractor
that may be broadly compatible with
the Europa subsurface ocean.

**This is not a claim that we should
send organisms to Europa now.**
It is the geometric observation that
the dimensional requirements for
life in Europa-class environments are
calculable using the same framework
that derives the dimensional requirements
for Ediacaran-class organisms.

The calculation is the same.
The environmental parameters are
different. The designed genome
is different. The principle is identical.

### 4.4 The Broader Principle

**[GEOMETRIC DERIVATION]**

The framework establishes that:

1. Every environment defines an
   attractor landscape — the set of
   stable states accessible given
   the physical and chemical parameters
   of that environment.

2. Life is what occupies an attractor
   in that landscape.

3. Whether life exists in a given
   environment is determined by whether
   any of the accessible attractors
   are occupied.

4. Whether life can be made to exist
   in a given environment is determined
   by whether any of the accessible
   attractors can be reached by a
   designed developmental program.

This is the geometric basis for
believing that life is not rare.
Any environment that defines at least
one stable attractor — any environment
where self-organization produces a
persistent structure — is an environment
where life is in principle possible.

The question "is there life elsewhere
in the universe?" becomes geometrically:

> "Are there other environments that
> define stable attractor basins
> accessible to molecular self-
> organization?"

The answer, from chemistry and
thermodynamics, is almost certainly
yes. The conditions for stable
molecular attractors — redox gradients,
liquid solvent, organic chemistry —
are widespread in the universe.

Life may be rare in practice because
the probability of spontaneously
navigating from chemistry to a stable
self-replicating attractor is low.

But **designed life** — life constructed
from a first-principles dimensional
calculation calibrated to a specific
environment — does not need to navigate
that probability. It needs only to
start at the right point in attractor
space.

**This is why the prediction is correct.**

The constructibility of life follows
directly from the framework. If the
attractor is calculable, the organism
is constructible. If the organism is
constructible, it can be calibrated
to any environment that defines a
compatible attractor. If it can be
calibrated to any such environment,
then the seeding of life onto other
worlds — the literal creation of alien
organisms — is a question of engineering,
not of principle.

---

## PART V — THE HONEST QUALIFICATIONS

This framework does not claim that
any of this is easy or imminent.
The following qualifications are
stated precisely:

**Qualification 1: The dimensional
calculation has not been validated.**
The estimate of ~660–665 dimensions
for an Ediacaran-class organism is
a first-principles derivation, not
an empirical measurement. The actual
number could be higher (if more gene
interactions are required than
estimated) or lower (if some modules
are simpler than the basal animal
analogs suggest). Validation requires
construction.

**Qualification 2: Eukaryotic synthetic
biology is 5–10 years behind
prokaryotic synthetic biology.**
The construction protocol described
here requires a minimal eukaryotic
chassis. This does not yet exist in
the form required. The synthetic
yeast genome project (Sc2.0) is
the closest current effort, but
it is focused on replacing existing
yeast chromosomes, not constructing
a minimal eukaryote from scratch.

**Qualification 3: The step from
a laboratory bioreactor to a planetary
environment is enormous.**
Even if the construction protocol
succeeds in the laboratory, deploying
designed organisms to other worlds
raises planetary protection concerns
that must be addressed with ethical
and scientific rigor. The framework
does not resolve these — it only
establishes that the geometric
principle is sound.

**Qualification 4: Coherence is not
truth.** The framework predicts what
an Ediacaran-class organism should
look like and what genome it should
have. These predictions are
geometrically coherent. They are
not empirically validated until
construction and testing occur.

---

## PART VI — THE NOVEL PREDICTIONS
## STATED AS FALSIFIABLE TESTS

| Prediction | Test | Failure Condition |
|---|---|---|
| An Ediacaran-class organism can be constructed with a ~650–800 gene genome encoding the five modules described | Construct the organism using the protocol in Part III | If the organism requires significantly more than 800 genes to achieve stable multicellularity and axis specification, the dimensional estimate is wrong |
| The attractor landscape of the designed genome, computed before construction, correctly predicts the organism's morphology | Compare computational attractor landscape prediction to observed morphology in the bioreactor | If the observed form systematically differs from the predicted form, the attractor landscape calculation method is insufficient |
| The constructed organism is viable in an Ediacaran-proxy environment (low O₂, marine, soft substrate) and non-viable in conditions significantly outside this range | Test in the designed environment and in environments varying each parameter independently | If the organism is viable outside its predicted attractor, the environmental dimensional calculation is wrong |
| Increasing the number of environmental parameter dimensions that are outside the viable range increases mortality in a predictable way | Environmental stress testing across all 7–10 environmental dimensions | If mortality does not scale with the number of simultaneously violated parameters, the multi-dimensional attractor model is incorrect |
| The same first-principles dimensional calculation applied to a non-Ediacaran environment produces a designable genome for that environment | Apply the protocol to a Mars-subsurface proxy environment | If no viable attractor is calculable for the Mars-subsurface environment, either the environment has no accessible attractors or the calculation method is incomplete |

---

## PART VII — THE SINGLE STATEMENT

The attractor geometry framework
makes life constructible from
first principles.

The Ediacaran organisms are the correct
first target because they are the
lowest-dimensional multicellular
organisms whose geometry is recorded
in the fossil record — approximately
660 regulatory dimensions versus the
tens of thousands required for complex
animals.

If an organism can be constructed
from a geometric calculation of its
dimensional requirements, then the
same calculation applied to any
environment that defines an accessible
attractor produces the design
specification for life in that environment.

Life is not a miracle.
It is a geometric consequence of
environments that define stable
molecular attractors.

The constructibility of life and
the possibility of creating organisms
calibrated to other worlds follow
directly — not as speculation,
but as engineering problems whose
principles are now stated precisely
enough to be tested.

---

## DOCUMENT METADATA

```
Author: Eric Robert Lawson / OrganismCore
Date: 2026-03-12
Status: ACTIVE — MOST AMBITIOUS DERIVATION
  IN THIS REPOSITORY
Classification: First principles derivation
  of synthetic organism construction
  from attractor geometry
Research basis: JCVI minimal cell work,
  Ediacaran organism developmental
  analysis, Dickinsonia body plan
  studies, synthetic biology 2024
  advances, xenobot/anthrobot research,
  gene regulatory network attractor
  landscape tools, minimum oxygen
  requirements for Precambrian life,
  planetary science (Mars/Europa)
Novel predictions: 5 (see Part VI)
Key insight: Ediacaran organisms are
  ~660-dimensional attractor constructions
  — within the range of current
  synthetic biology. If a genome can
  be designed from this dimensional
  calculation and validated in a
  laboratory bioreactor, the framework
  achieves its strongest possible
  empirical proof: not just predicting
  cancer drug targets, but constructing
  a living organism from geometry alone.
Falsifiability: All predictions in
  Part VI carry explicit test conditions
  and failure criteria.
Version: 1.0
```
